apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: web
  name: web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: adinaclaudiatoma/node-sample:v2
        name: web
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
            name: http-server
        env:
          - name: MONGODB_ADDON_URI
            value: "mongodb://mongo:27017"
        # if app fails liveness, pod will be restarted
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          failureThreshold: 3
        # tells the Kubernetes service (~load balancer) that the traffic can be redirected to the specific pod.
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          failureThreshold: 1
