apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv
  labels:
    type: aws
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0e2ddf01833f1aa63
    fsType: ext4