kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: slow