apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: docker
    image: docker
    command: ["/bin/sh", "-c"]
    args: 
      - > 
        apk --update add curl ;
        while true; 
          sleep 5;
          do curl -I http://localhost:80 ; 
        done

