apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 32001
  selector:
    name: web
