apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm-volume
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html
  - name: docker
    image: docker
    env:
    - name: SOME_ENV_VAR
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: literal1
    - name: SOME_OTHER_ENV_VAR
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: literal2
    command: ["/bin/sh", "-c", "while true ; do env | sort; sleep 5; done"]
  volumes:
  - name: config-volume
    configMap:
      name: some-config4
      items:
      - key: kubernetes.io
        path: index.html
